# Generated by Django 5.2.7 on 2025-12-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_initial"),
        ("students", "0003_remove_studentprofile_user_student_studentenrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="students.student",
            ),
        ),
    ]
