# Generated by Django 5.2.7 on 2025-12-21 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("excused", "Excused"),
                        ],
                        max_length=10,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=200)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("grade_level", models.CharField(max_length=10)),
                ("section", models.CharField(max_length=5)),
                ("attendance_data", models.JSONField(default=dict)),
                ("total_present", models.IntegerField(default=0)),
                ("total_absent", models.IntegerField(default=0)),
                ("total_late", models.IntegerField(default=0)),
                ("total_half_day", models.IntegerField(default=0)),
                ("total_excused", models.IntegerField(default=0)),
                ("working_days", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="student",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="subject",
        ),
        migrations.CreateModel(
            name="AttendanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=9, unique=True)),
                ("working_days_per_week", models.IntegerField(default=6)),
                (
                    "minimum_attendance_percentage",
                    models.DecimalField(decimal_places=2, default=75.0, max_digits=5),
                ),
                ("late_marks_threshold", models.IntegerField(default=3)),
                ("auto_calculate_totals", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
