# Generated by Django 5.2.7 on 2025-12-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_dailyattendancelog_monthlyattendance_and_more"),
        ("students", "0003_remove_studentprofile_user_student_studentenrollment"),
        ("teachers", "0003_remove_teacherprofile_user_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyattendancelog",
            name="marked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teachers.teacher"
            ),
        ),
        migrations.AddField(
            model_name="dailyattendancelog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="monthlyattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.AddIndex(
            model_name="dailyattendancelog",
            index=models.Index(
                fields=["student", "date"], name="attendance__student_63ba7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendancelog",
            index=models.Index(
                fields=["date", "status"], name="attendance__date_258b43_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyattendancelog",
            unique_together={("student", "date")},
        ),
        migrations.AddIndex(
            model_name="monthlyattendance",
            index=models.Index(
                fields=["student", "month", "year"],
                name="attendance__student_ad0ec2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyattendance",
            index=models.Index(
                fields=["grade_level", "section", "month", "year"],
                name="attendance__grade_l_853c24_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyattendance",
            unique_together={("student", "month", "year")},
        ),
    ]
