# Generated by Django 5.2.7 on 2025-11-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tearher_id", models.CharField(max_length=50, unique=True)),
                ("subject_specialization", models.CharField(max_length=100)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("contact_no", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
