# Generated by Django 5.2.7 on 2025-12-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_alter_announcement_posted_by_and_more"),
        ("assignments", "0003_alter_assignment_assigned_by_and_more"),
        ("subjects", "0004_alter_subject_teacher"),
        ("teachers", "0003_remove_teacherprofile_user_teacher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeacherProfile",
        ),
    ]
