# Generated by Django 5.2.7 on 2025-12-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_initial"),
        ("students", "0003_remove_studentprofile_user_student_studentenrollment"),
        ("teachers", "0003_remove_teacherprofile_user_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assignments",
                to="teachers.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="students.student",
            ),
        ),
    ]
