# Generated by Django 5.2.7 on 2025-12-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("national", "National Holiday"),
                            ("regional", "Regional Holiday"),
                            ("school", "School Holiday"),
                            ("exam", "Exam Holiday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("date", "academic_year")},
            },
        ),
    ]
