# Generated by Django 5.2.7 on 2025-10-21 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("announcements", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="posted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_announcements",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_announcements",
                to="teachers.teacherprofile",
            ),
        ),
    ]
