# Generated by Django 5.2.7 on 2025-12-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_initial"),
        ("teachers", "0003_remove_teacherprofile_user_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="posted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_announcements",
                to="teachers.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_announcements",
                to="teachers.teacher",
            ),
        ),
    ]
