# Generated by Django 5.2.7 on 2025-12-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("grade_level", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=100)),
                ("academic_year", models.CharField(max_length=100)),
                ("room_number", models.CharField(blank=True, max_length=10)),
                ("capacity", models.IntegerField(default=40)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Classes",
            },
        ),
    ]
