# Generated by Django 5.2.7 on 2025-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=50, unique=True)),
                ("grade_level", models.CharField(max_length=20)),
                ("class_name", models.CharField(max_length=50)),
                (
                    "guardian_contact",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
        ),
    ]
