# Generated by Django 5.2.7 on 2025-12-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_assignment_assigned_by_and_more"),
        ("attendance", "0005_dailyattendancelog_marked_by_and_more"),
        ("grades", "0004_alter_grade_student"),
        ("students", "0003_remove_studentprofile_user_student_studentenrollment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentProfile",
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("student", "class_obj")},
        ),
    ]
