# Generated by Django 5.2.7 on 2025-12-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classSubjects", "0001_initial"),
        ("classes", "0001_initial"),
        ("subjects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsubject",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="classes.class",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="subjects.subject",
            ),
        ),
    ]
