# Generated by Django 5.2.7 on 2025-12-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classSubjects", "0002_initial"),
        ("teachers", "0003_remove_teacherprofile_user_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsubject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="teachers.teacher",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_obj", "subject")},
        ),
    ]
